### ISSUE TITLE
iPad doesn’t show header and footer just the fullscreen preview.

### ISSUE THREAD

**Issue by lfiorini** [moaazsidat/react-native-qrcode-scanner#118]
I’ve added universal support to my apps and I found that it reads the barcode, but there is no header or footer. Is it expected?

iPad Air 2, iOS 11.4, latest qrcode-scanner version, RN 0.55.4.

**Comment by moaazsidat** [comment]
@lfiorini I have not been able to test this out on an iPad, it may just be a styling issue?

**Comment by renatobenks** [comment]
closing this one by the long inactivity around this, especially because it's probably related to viewport issues around the react components in react native instead of bad behavior from this, so let me know if you're still having any troubles with that @lfiorini or which workaround did you used to solve that
