### ISSUE TITLE
NSLocationAlwaysUsageDescription issue due to dependencies

### ISSUE THREAD

**Issue by zkrige** [moaazsidat/react-native-qrcode-scanner#129]
### What's happening?
When submitting to app store, I am getting a NSLocationAlwaysUsageDescription error. This is because this package relies on react-native-permissions, which covers ALL permissions.

### How can it be reproduced?
n/a

### Build details?
seeing this in 1.0.1

My suggestion would be to either build a camera-permissions only package and depend on that, OR handle camera permissions in your code directly

**Comment by betoharres** [comment]
Looking at the code it seems like the author invoked only the camera permission from that package. Does your app uses GPS? Maybe you're mixing the problems. 

PS: I just downloaded the lib and was looking about the issues in this repo, don't take my word for experience with this lib, I'm just trying to help :D

**Comment by moaazsidat** [comment]
Accepting PRs to fix this issue :)

**Comment by poltak** [comment]
I was also looking into this, as I got all the permission errors on app store submission, and found this thread.

Looking into the `react-native-permissions` package, they seem to be aware of this issue and explain it a bit more in the README stating that these permissions won't actually be shown to the users unless you really require them in your app:
https://github.com/react-native-community/react-native-permissions#app-store-submission-disclaimer

There is also an issue about this exact problem over there, with some proposed solutions, although nothing was done about it and it seems like no further plans to address it:
https://github.com/react-native-community/react-native-permissions/issues/46

I know this isn't a solution to this thread, but at least I can relax a bit knowing that users won't have the impression we're requiring all these permissions we're not actually using. I *think* that is enough for me for now

**Comment by renatobenks** [comment]
thank you for this disclaimer about this issue @poltak, it really helps!

**Comment by renatobenks** [comment]
First of all, this is not an issue in `react-native-qrcode-scanner` because it's totally related to the `react-native-permissions` package as the 
@poltak told it above and as he shared with us, you can take a look in the following thread to take some help with this problem https://github.com/react-native-community/react-native-permissions/issues/46

By the way, it was a really good disclaimer about it, so thanks for that @poltak.

But anyway, I took a deeper look into it to understand better the thread around this issue related to this one and what was going on over there to work or maybe share a workaround for that in our side. But I realized that it's a problem already solved since version `>2.0.0` as described in the following comment https://github.com/react-native-community/react-native-permissions/issues/46#issuecomment-532990603.

So, using the latest version of `react-native-permissions`, or just since the `v2.0.0` version, everything should be working fine.

Then, no more reasons to keep this issue open, so I'll be closing it!

In the case of face a related problem, where the permissions are not working properly well as expected on using this package, please, open an issue in the https://github.com/react-native-community/react-native-permissions instead.
