### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by francescossoru** [moaazsidat/react-native-qrcode-scanner#207]
There's a problem with permissions from October please fix it

**Comment by theoctober19th** [comment]
Same here. getting permissions error in iOS. There is a pull request that fixes my problem which have not yet been merged.

**Comment by moaazsidat** [comment]
yes, it is, however, due to the contributors' time being limited, some issues and PRs may not get attention, with an upper bound of around 4 months at times. Please see the last line at the intro on the readme: https://github.com/moaazsidat/react-native-qrcode-scanner

we're constantly on the look out for active contributors :) 
if you'd like to take on that responsibility, please do reach out
