### ISSUE TITLE
Any example for android device?

### ISSUE THREAD

**Issue by Dannnyho** [moaazsidat/react-native-qrcode-scanner#23]
NavigatorIOS is not working for android, is there any sample for android development?

**Comment by moaazsidat** [comment]
hey @Dannnyho 

since QRCodeScanner is just a React component, you can always render it like so
```
import QRCodeScanner from 'react-native-qrcode-scanner'

<QRCodeScanner
  title='Scan Code'
  onRead={() => alert('Success')}
  topContent={(
    <Text style={styles.centerText}>
      Go to <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on your computer and scan the QR code.
    </Text>
  )}
  bottomContent={(
    <TouchableOpacity style={styles.buttonTouchable}>
      <Text style={styles.buttonText}>OK. Got it!</Text>
    </TouchableOpacity>
  )}
/>
          
```

**Comment by MTGHO** [comment]
When I put QRCodeScanner component in a View everything disappears in android!But it works on iphone!
I need it works on android too
my code: 
```
render() {
        return (
            <View>
                <QRCodeScanner
                    title='Scan Code'
                    onRead={this.onSuccess.bind(this)}
                    bottomContent={(
                        <Text style={styles.centerText}>{"\n"}Scan the QR code</Text>
                    )}
                />
            </View>
        );
    }
```

**Comment by moaazsidat** [comment]
@Dannnyho @MTGHO added an Android example:
https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/examples/default.android.js

Tested on the Android studio emulator:
<img width="331" alt="screenshot 2017-10-03 16 01 35" src="https://user-images.githubusercontent.com/5963656/31153252-d02599bc-a854-11e7-8241-6113e269cc44.png">


@MTGHO with respect to the code snippet you added above, please ensure your `View` element has the flex style set to it, otherwise there may be styling issues with wrapping the `QRCodeScanner` in `View`. Let me know if you have any other questions. 

Closing this for now, please reopen if the Android example is still an issue.
