### ISSUE TITLE
[!] use_native_modules! skipped the react-native dependency 'react-native-qr-scanner'. No podspec file was found.

### ISSUE THREAD

**Issue by suraneti** [moaazsidat/react-native-qrcode-scanner#248]
The library doesn't support use_native_modules?

### What's happening?

Warning `[!] use_native_modules! skipped the react-native dependency 'react-native-qr-scanner'. No podspec file was found.`

### How can it be reproduced?

1. Install the library following instructions.
2. pod install.

### Build details?

macOS Mojave 10.14.6
```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-camera": "^3.17.0",
"react-native-qr-scanner": "^1.3.2",
```

**Comment by renatobenks** [comment]
@suraneti there are a couple of things that I wanna share to you to help with this:

- you're not using this package because you're actually using this following one https://www.npmjs.com/package/react-native-qr-scanner as defined at `package.json` as you described it here
- the problems that showed up to you it's not a problem at all, it's actually just a WARNING because this package that you're using, is a native module as the `react-native-camera` is but is not configured to the react-native auto-linking work together which is causing this WARNING message, because the integration will not gonna work with the module link missing, so probably you didn't run the `react-native link` to this project as well
- as I look into this another package it sounds to be deprecated, so it does not seem to be the best package fit to integrate a module to scan QR codes, so I would like to suggest to you to switch the package to use this one instead where we can help you better with

Anyway, I'll be closing this but let me know if you have any other problems to use the `react-native-qrcode-scanner` instead 😄
