### ISSUE TITLE
hello , I intall the lib. react native Qr scanner and i get an error

### ISSUE THREAD

**Issue by shubhamjz** [moaazsidat/react-native-qrcode-scanner#251]

**Comment by renatobenks** [comment]
hey @shubhamjz, can you describe it better telling us what exactly is the error that you're facing, please? I believe that just filling the fields, as suggested in the description of this issue, would be enough to help you as you need (:

by the way, it would be good to have a better title as well, because this issue could be useful for someone else facing the same problem 👌

**Comment by renatobenks** [comment]
closing this by inactivity and the missing of information, let me know if you're still having this problem @shubhamjz
