### ISSUE TITLE
Best practice: Transform js object to QR code

### ISSUE THREAD

**Issue by ASchwad** [moaazsidat/react-native-qrcode-scanner#263]
Hey there,

I am trying to convert a classic javascript object to a QR Code.

`var car = {type:"Fiat", model:"500", color:"white"}`

My current approach is to take each value and create one long string, which i handover as "byte"

`value={[{ data: 'Fiat#500#white', mode: 'byte' }]}`

Is there a more elegant way? I would like to read the data via another phone and get the object.

Thanks in advance!

**Comment by renatobenks** [comment]
I'm not sure that I've got you right about what you want to do, but perhaps you're asking for in the wrong place because this package it's only responsible to read generated QR code's and not to generate them, and as your problem looks describe that you're just trying to generate a QR code it doesn't to be related to this package at all. So probably you'll gonna have better support by asking for that in the library that you're using to that, like this one https://github.com/soldair/node-qrcode.

So, just for tracking reasons and to keep it up-to-date with their real status, I'll gonna be closing this one. However, independently of this been closed or not, I'll try to help you with that anyway.

So, can you tell me which component with such a prop `value` that you're trying to use to create a QR code to be read? Is this one https://github.com/awesomejerry/react-native-qrcode-svg?

**Comment by ASchwad** [comment]
Sorry, I have meant to post this issue in https://github.com/awesomejerry/react-native-qrcode-svg.

**Comment by renatobenks** [comment]
great @ASchwad, let me know if you've experienced any issues around this package, or even to any other related to that
