### ISSUE TITLE
Is it possible to read qrcode from an image

### ISSUE THREAD

**Issue by rajneshbiz** [moaazsidat/react-native-qrcode-scanner#264]
I use react-native-qrcode-scanner to scan QR-code and it works well, But I need to Read QR-code from the captured image.

Is it possible with QRCodeScanner?

**Comment by renatobenks** [comment]
Sorry, unfortunately, this is not supported currently! But it's definitely a pretty good case to build a feature to support that. Then, in order to make it possible in the future as this is a good feature suggest to be built, I've created this another issue #265 to work on it.

I'm not sure if you already did find a workaround to make it work, but in this case, it would be great to have this as an example of workaround to share with someone else looking for the same thing, and in the case of you didn't get it yet, no worries, I'll try to find any workaround to support that in advance. So, in the meanwhile, we’ll gonna share it in the issue of this feature request in. Until there, we won't be able to support this feature officially.
