### ISSUE TITLE
Unable to install latest version 1.5.0

### ISSUE THREAD

**Issue by manohar-octifi** [moaazsidat/react-native-qrcode-scanner#276]
### What's happening?
Tried to install latest version (1.5.0) of package to use cameraTimeout prop but got 1.4.1 as the latest 

### How can it be reproduced?
npm i react-native-qrcode-scanner@latest

### Build details?
Mac OS, RNQS 1.4.2

**Comment by renatobenks** [comment]
thank you for opening this @manohar-octifi, and letting us know about that.

@moaazsidat can you update the `v1.5.0` version at npm, please? it should be the latest one over there but it's not, because we miss to upgrade it on npm as well.

for instance @manohar-octifi, you can use the tag on git for now as a package definition on npm, using this tag https://github.com/moaazsidat/react-native-qrcode-scanner/tree/v1.5.0, it should works until we have the latest version updated at npm.

let me know if it worked well, and what else I can help you with.

**Comment by abumalick** [comment]
@moaazsidat We need the last version on npm please

**Comment by bramski** [comment]
3 months and zero activity @moaazsidat please update NPM.

**Comment by moaazsidat** [comment]
Apologies, haven't been too active on this repo, just published 1.6.0

Also opened an issue to fix it with CI so that it doesn't rely on manual publishing
https://github.com/moaazsidat/react-native-qrcode-scanner/issues/302
