### ISSUE TITLE
how can i check if permission denied for camera

### ISSUE THREAD

**Issue by jawwad22** [moaazsidat/react-native-qrcode-scanner#285]
Hi, if user go to a qr scanner screen first time, permission dialog popup, if user allow permission then everythings good, but if user denied the permission then there is message show "Camera is not authorize",

now what i want that, if user denied, then there should be function run which navigate back the screen and when user come back to screen then again camera permission dialog show

thank you, i hope you understand the issue, it can be a enhancement for package

**Comment by renatobenks** [comment]
in order to support such behavior, you'll gonna have to take a look on https://github.com/react-native-community/react-native-permissions#understanding-permission-flow, which explains exactly how does work the permissions workflow in `react-native-permissions` which it's one of our peer dependencies
