### ISSUE TITLE
react-native-permission: NativeModule.RNPermission is null

### ISSUE THREAD

**Issue by omshiv12** [moaazsidat/react-native-qrcode-scanner#300]

**Comment by Kuhne1** [comment]
I just installed the library, Issue I had with permissions was that it was locking the version to 2. when the latest docs are on v3.
Try out the following steps and let me know if it works for you. 
firstly uninstall the libraries
npm uninstall react-native-qrcode-scanner
npm uninstall react-native-permissions
Then in this order
npm install react-native-permissions (check your package.json you have version 3.0.0, the repo was locking me 2.3)
npm install github:moaazsidat/react-native-qrcode-scanner (The owner of the repo has not updated the npm link so you are getting the old version)

Update you podfile
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera" (Or whatever permission you want here)

Pod install

And run :) Goodluck

**Comment by kolkol69** [comment]
For me the problem was appearing because I couldn't install pods, in readme it says to paste this in podfile:
permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera <strike>.podspec</strike> "

but actually permissions should be without `.podspec`

**Comment by moaazsidat** [comment]
Just merged a PR with the update to the readme, thanks for the catch!
