### ISSUE TITLE
Need to stop auto scanning barcode

### ISSUE THREAD

**Issue by bhargav-simejiya** [moaazsidat/react-native-qrcode-scanner#346]
Need to stop auto scanning barcode and need capture button in camera

### What's happening?
If there are lots of barcode and trying to scan specific barcode but always first visible barcode from camera

thanks in advance

**Comment by renatobenks** [comment]
I see it! Actually, by design, barcodes are reached automatically, however, looking to this case, you could use a workaround to solve that problem. Try to use https://github.com/react-native-camera/react-native-camera/blob/941536592cb8ad6f65f3cb50e2fe814b7c70c093/docs/RNCamera.md#autofocuspointofinterest this feature from RNCamera, which you're able to access through `cameraProps` in QRCodeScanner.

That's pretty much how people has dealing with this problem. Otherwise, you could also use the activation flag for allowing the camera to know when it should scan something.
