### ISSUE TITLE
Error: react-native-permissions: NativeModule.RNPermissions is null.

### ISSUE THREAD

**Issue by Gomez0015** [moaazsidat/react-native-qrcode-scanner#348]
I have tried everything I could find and nothing worked.

### What's happening?
I am trying to use the QRCodeScanner Component and this happens, Without it, my app runs fine.

### How can it be reproduced?
Make a new expo init Test
then install the basics and add a QR Code Component, add permissions in the ios folder and that's where I'm at.

### Build details?
IOS 14.6 QR Code Scanner 1.5.4

PLease help me have been stuck at this for hours.

**Comment by renatobenks** [comment]
Well, first off, make sure that you perfectly have executed all the steps to install react-native-permission, including the additional ones. Second, so far I know, if you're not working with expo ejected, it'll not gonna work properly with expo, because expo already manages it to you in a different way.
