### ISSUE TITLE
Check The render Method of QRCodeScanner

### ISSUE THREAD

**Issue by nagacoder** [moaazsidat/react-native-qrcode-scanner#78]
Android
i am was import QRCodeScanner Component to my index page
this my example code 
`import React, {Component} from "react";`
`import QRCodeScanner from 'react-native-qrcode-scanner';`
`class QRCoder extends Component {`

`  onSuccess(e) {`
 ` Linking.openURL(e.data).catch(err => console.error('An error occured', err));`
`}`
  `render() {`
    `return (`
     ` <QRCodeScanner/>`
      `);`
  `}`
`}`

`export default QRCoder;`

and then i got an error 

Invariant Violation: Element type is invalid: expected a string( for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in

Check The render Method of "QRCodeScanner"

**Comment by moaazsidat** [comment]
you're missing the `onRead` prop which is required, feel free to use examples [here](https://github.com/moaazsidat/react-native-qrcode-scanner/tree/master/examples)

**Comment by nagacoder** [comment]
![error](https://user-images.githubusercontent.com/32693625/38170046-32a97e36-35a5-11e8-9c84-5ca6042c484d.png)
thanks for your replay , but its not solved, i am try use the example code for default android, but i am got same the error ,

are you have another example QRCoder implement for android?

this my full code  but not working

`import React, { Component } from 'react';`

`import {`
`  AppRegistry,`
  `StyleSheet,`
 ` Text,`
  `Navigator,`
  `TouchableOpacity,`
  `Linking,`
`} from 'react-native';`

`import QRCodeScanner from 'react-native-qrcode-scanner';`

`class QRCoder extends Component {`
  `onSuccess(e) {`
    `Linking`
     ` .openURL(e.data)`
      `.catch(err => console.error('An error occured', err));`
  `}
`
 ` render() {`
    `return (`
      `<QRCodeScanner`
        `onRead={this.onSuccess.bind(this)}`
        `topContent={(`
          `<Text style={styles.centerText}>`
            `Go to <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on your computer and scan the QR code.`
         ` </Text>`
        `)}`
        `bottomContent={(`
          `<TouchableOpacity style={styles.buttonTouchable}>`
            `<Text style={styles.buttonText}>OK. Got it!</Text>`
          `</TouchableOpacity>`
       ` )}`
      `/>`
   ` );`
 ` }`
`}`

`const styles = StyleSheet.create({`
  `centerText: {`
   ` flex: 1,`
   ` fontSize: 18,`
    `padding: 32,`
   ` color: '#777',`
 ` },`

 ` textBold: {`
   ` fontWeight: '500',`
    `color: '#000',`
 ` },`

  `buttonText: {`
    `fontSize: 21,`
    `color: 'rgb(0,122,255)',`
 ` },`

  `buttonTouchable: {`
    `padding: 16,`
  `},`
`});`

`export default QRCoder;`

**Comment by yazpid** [comment]
I'm have the same isssue like above. Also copied expamle from documentation.

**Comment by moaazsidat** [comment]
Hey folks, thanks again for reaching out! Unfortunately I don't have a machine with the Android setup ready to test this out and debug it over the next couple of months, please feel free to look deeper into this, I'm [also looking for an active Android dev to help be a core contributor](https://github.com/moaazsidat/react-native-qrcode-scanner/issues/59) if that interests you. 

As a start, it may be a [recent migration](https://github.com/moaazsidat/react-native-qrcode-scanner/pull/76) that's causing this issue, however, things were working fine on iOS when I tested it out earlier last week. 

We were unable to have it tested on Android devices, but still needed to push the release since react-native-camera's newer versions were no longer compatible with the old version of this library. 

Also check out the [migration guide here](https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/migration.md) if you're using the latest version to see if you're missing anything specific in the setup/build process. 

Please keep this thread updated and let me know if any of the above helps, thanks!

**Comment by miguelzau** [comment]
Hi, i use this version:
"react-native-camera": "^1.0.3",
"react-native-qrcode-scanner": "^1.0.0"
and no problem with the render method. before i have the error because i use a react-native camera version < 1.0.0

**Comment by nagacoder** [comment]
Thanks @miguelzau  its work fine,  just "upgrade version react-native-camera": "^1.0.3",

**Comment by jituumaria** [comment]
why support fullscreen android and ios both ?..

**Comment by agusryank** [comment]
hy i am having a same issues like this, how can i solve this problems ?  the version is "react-native-camera": "^4.2.1",  "react-native-qrcode-scanner": "^1.5.4", should i downgrade it or upgrade ??
