### ISSUE TITLE
Using `react-native-qrcode-scanner` with `create-react-native-app`

### ISSUE THREAD

**Issue by ndsmith2280** [moaazsidat/react-native-qrcode-scanner#91]
### What's happening?

When I run the `react-native link react-native-camera` command I get the following output:
```
Scanning folders for symlinks in /Users/nsmith6005/GitHub/herkyles/node_modules (15ms)
```
It seems to be doing nothing

When I run the `react-native link` command I get the following error:
```
Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null
```

According to [Graham42](https://github.com/Graham42) @ [Issue #556](https://github.com/react-community/create-react-native-app/issues/556); it looks like I might need to eject inorder to use `react-native-qrcode-scanner`. Is this the case?

**Comment by jeffvandyke** [comment]
I looked into this for a simple app, and decided to use Expo's Camera component (see <https://docs.expo.io/versions/latest/sdk/camera> for docs), making use of the onBarCodeRead callback property (see <https://docs.expo.io/versions/latest/sdk/camera#onbarcoderead-function>), and that, combined with their example, works very well and allows for plenty of customization.

It does appear, that with this `react-native-qrcode-scanner` app, you need to have ejected in order to use it. I'm keeping my use of Expo's Camera component behind another component so that it could be rewritten easily if I drop Expo - avoid vendor lockin!

**Comment by moaazsidat** [comment]
yep, as @jeffvandyke mentioned, you're better off using Expo's camera component when using Expo, this library is primarily designed to work with the ejected version or in other words, a setup that is run using the `react-native` cli as it relies on linking. 

If anyone in the community has experience integrating libraries with the Expo ecosystem, I'd be happy to entertain PRs attempting that. 

Going to close this issue for now.
